version: "3.9"
services:
  mariadb:
    build: ./requirements/mariadb
    networks:
      - intra
    env_file:
      - .env
    volumes:
      - ./vol_mariadb:/var/lib/mysql
    restart: always
  wordpress:
    build: ./requirements/wordpress
    networks:
      - intra
    env_file:
      - .env
    volumes:
      - ./vol_wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    restart: always
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - intra
    env_file:
      - .env
    volumes:
      - ./vol_wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always
networks:
  intra:
